version: '3.8'
services:
  api:
    container_name: message-api
    build:
      dockerfile: Dockerfile
      context: .
      args:
        APP_PORT: ${APP_PORT}
        DB_HOST: ${DB_HOST}
        DB_PORT: ${DB_PORT}
        DB_USERNAME: ${DB_USERNAME}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_DATABASE: ${DB_DATABASE}
        TWILIO_ACCOUNT_SID: ${TWILIO_ACCOUNT_SID}
        TWILIO_AUTH_TOKEN: ${TWILIO_AUTH_TOKEN}
        TWILIO_MESSAGING_SERVICE_SID: ${TWILIO_MESSAGING_SERVICE_SID}
        REDIS_HOST: ${REDIS_HOST}
        REDIS_PORT: ${REDIS_PORT}
        REDIS_PASSWORD: ${REDIS_PASSWORD}
        JWT_SECRET: ${JWT_SECRET}
        TYPEORM_LOGGING: ${TYPEORM_LOGGING}
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - mariadb
      - redis
    networks:
      - message-network
  mariadb:
    container_name: message-db
    image: mariadb:10.10.2
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: UTC
    ports:
      - ${DB_PORT}:${DB_PORT}
    restart: on-failure
    networks:
      - message-network
  redis:
    container_name: message-cache
    image: redis:7.0.7-alpine
    restart: on-failure
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    command: "redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}"
    volumes:
      - ${PWD}/redis:/data
    networks:
      - message-network
networks:
  message-network: {}
