version: '3.8'
services:
  mariadb:
    image: mariadb:10.10.2
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: UTC
    ports:
      - ${DB_PORT}:${DB_PORT}
    restart: on-failure
    volumes:
     - ${PWD}/mariadb:/var/lib/mysql
  redis:
    image: redis:7.0.7-alpine
    restart: on-failure
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    command: "redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}"
    volumes: 
      - ${PWD}/redis:/data
volumes:
  mariadb:
    driver: local
  redis:
    driver: local