version: '3.8'
services:
  mariadb:
    image: mariadb:10.10.2
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: sendme
      MYSQL_USER: sendme
      MYSQL_PASSWORD: 123456
    ports:
      - '3306:3306'
    restart: on-failure
    volumes:
     - ${PWD}/mariadb:/var/lib/mysql
  redis:
    image: redis:7.0.7-alpine
    restart: on-failure
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - ${PWD}/redis:/data
volumes:
  mariadb:
    driver: local
  redis:
    driver: local